spring.application.name=hospital-meal-service

server.port=8081
# Nacos ??????
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
# ??????????
spring.profiles.active=local

# ???hospital-server?????JWT????
jwt.secret=${JWT_SECRET:9N7JfWEx727PM1IQ8Tir3u7y2/cqnfcdKs+dIACNPdo=}

# RocketMQ 5.x SDK ???? Proxy ????? NameServer ??
rocketmq.endpoints=127.0.0.1:18081

# ????????
rocketmq.topic.order-timeout=meal-order-timeout-topic

# ???????????????????
rocketmq.consumer-group.order-timeout=meal-order-timeout-consumer