brokerClusterName=HospitalMealCluster
brokerName=hospital-meal-broker
brokerId=0

# Broker 对宿主机公布的地址
brokerIP1=127.0.0.1

# Broker 服务端口
listenPort=10911

# 每天凌晨4点清理过期文件
deleteWhen=04

# 消息文件保存48小时
fileReservedTime=48

# 单节点开发环境使用异步主节点
brokerRole=ASYNC_MASTER

# 异步刷盘
flushDiskType=ASYNC_FLUSH

# 本地开发自动创建Topic和消费组
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true